// Generated by scripts/generate-radio.ps1. Imported assets stay out of Android.
import type { RadioId } from './tactical-radio';
import command_online from '../web/audio/radio/command_online.wav';
import enemy_approaching from '../web/audio/radio/enemy_approaching.wav';
import target_destroyed from '../web/audio/radio/target_destroyed.wav';
import multiple_targets from '../web/audio/radio/multiple_targets.wav';
import boss_detected from '../web/audio/radio/boss_detected.wav';
import boss_escalating from '../web/audio/radio/boss_escalating.wav';
import boss_final_assault from '../web/audio/radio/boss_final_assault.wav';
import boss_destroyed from '../web/audio/radio/boss_destroyed.wav';
import incoming_barrage from '../web/audio/radio/incoming_barrage.wav';
import armor_low from '../web/audio/radio/armor_low.wav';
import armor_critical from '../web/audio/radio/armor_critical.wav';
import armor_restored from '../web/audio/radio/armor_restored.wav';
import mine_deployed from '../web/audio/radio/mine_deployed.wav';
import hostile_mines from '../web/audio/radio/hostile_mines.wav';
import mines_cleared from '../web/audio/radio/mines_cleared.wav';
import pulse_activated from '../web/audio/radio/pulse_activated.wav';
import ammo_low from '../web/audio/radio/ammo_low.wav';
import ammo_depleted from '../web/audio/radio/ammo_depleted.wav';
import objective_secured from '../web/audio/radio/objective_secured.wav';
import mission_complete from '../web/audio/radio/mission_complete.wav';
import mission_failed from '../web/audio/radio/mission_failed.wav';
export const RADIO_ASSETS: Record<RadioId, string> = {
  command_online,
  enemy_approaching,
  target_destroyed,
  multiple_targets,
  boss_detected,
  boss_escalating,
  boss_final_assault,
  boss_destroyed,
  incoming_barrage,
  armor_low,
  armor_critical,
  armor_restored,
  mine_deployed,
  hostile_mines,
  mines_cleared,
  pulse_activated,
  ammo_low,
  ammo_depleted,
  objective_secured,
  mission_complete,
  mission_failed,
};
