"""Package existing original music and licensed vehicle foley for the PC game.

No downloads or external service. Preserves separately prepared actor recordings.
Writes only pc-godot/assets/audio/battlefield.
"""
from pathlib import Path
import hashlib
import json
import shutil
import wave
import numpy as np

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'pc-godot/assets/audio/battlefield'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read(path):
    with wave.open(str(path), 'rb') as w:
        channels, rate = w.getnchannels(), w.getframerate()
        data = np.frombuffer(w.readframes(w.getnframes()), dtype='<i2').astype(float).reshape(-1, channels) / 32768
    return rate, data


def write(path, rate, data):
    with wave.open(str(path), 'wb') as w:
        w.setnchannels(data.shape[1]); w.setsampwidth(2); w.setframerate(rate)
        w.writeframes(np.rint(np.clip(data, -.94, .94) * 32767).astype('<i2').tobytes())


def metrics(path, loop=False):
    rate, data = read(path)
    result = dict(file=path.relative_to(OUT).as_posix(), bytes=path.stat().st_size,
        sha256=digest(path), sample_rate=rate, channels=data.shape[1],
        duration_seconds=len(data)/rate, peak=float(abs(data).max()),
        rms=float(np.sqrt(np.mean(data**2))), clipped_samples=int(np.sum(abs(data)>=.9999)))
    if loop:
        result['loop_seam_max'] = float(abs(data[0]-data[-1]).max())
        result['adjacent_step_rms'] = float(np.sqrt(np.mean(np.diff(data, axis=0)**2)))
    return result


def main():
    existing = json.loads((OUT/'provenance.json').read_text(encoding='utf-8'))
    for folder in ['music', 'vehicle', 'radio']:
        (OUT/folder).mkdir(parents=True, exist_ok=True)
    files = []
    for name in ['industrial-war', 'electronic-pursuit', 'epic-siege']:
        source = ROOT/f'public/music/{name}.wav'
        target = OUT/f'music/{name}.wav'
        shutil.copyfile(source, target)
        files.append(dict(**metrics(target, True), source=source.relative_to(ROOT).as_posix(),
            source_sha256=digest(source), processing='Unchanged original procedural composition; full-file forward loop.'))
    for name in ['track-engine', 'track-treads']:
        source = ROOT/f'web/audio/combat/{name}.wav'
        rate, data = read(source)
        # Remove residual boundary step using a short smooth endpoint correction.
        # Preserve the continuous ambience instead of fading the entire loop to silence.
        amount = round(.003*rate)
        delta = data[-1]-data[0]
        data[-amount:] -= (np.linspace(0, 1, amount)**2)[:,None]*delta
        target = OUT/f'vehicle/{name}.wav'
        write(target, rate, data)
        files.append(dict(**metrics(target, True), source=source.relative_to(ROOT).as_posix(),
            source_sha256=digest(source), processing='Existing licensed mono vehicle loop; smooth 3ms endpoint correction for seamless PCM wrap.'))
    source = ROOT/'web/audio/combat/track-treads.wav'
    rate, data = read(source)
    # Steering layer: filtered track friction and modal steel resonance. Original
    # mechanical sound design on credited garage-door tread foley, not a field recording.
    n = len(data); t = np.arange(n)/rate
    freq = np.fft.rfftfreq(n, 1/rate)
    response = np.exp(-.5*((freq-780)/500)**2)
    friction = np.fft.irfft(np.fft.rfft(data[:,0])*response, n=n)
    resonance = sum(.024*np.sin(2*np.pi*round(f*n/rate)*rate/n*t) for f in [138, 276, 415])
    turn = (.83*friction + resonance)[:,None]
    turn *= .58/max(abs(turn).max(), 1e-9)
    amount = round(.003*rate)
    turn[-amount:] -= (np.linspace(0,1,amount)**2)[:,None]*(turn[-1]-turn[0])
    target = OUT/'vehicle/track-turn.wav'; write(target, rate, turn)
    files.append(dict(**metrics(target, True), source=source.relative_to(ROOT).as_posix(),
        source_sha256=digest(source), processing='Circular FFT midrange friction filter, original harmonic steel resonance, seamless endpoint correction.'))
    # Regenerating the music/mechanics must never relabel recorded actors as
    # TTS, discard their original-source hashes, or restore obsolete speech.
    files.extend(record for record in existing['files'] if record['file'].startswith('radio/'))
    provenance = json.loads((ROOT/'web/audio/combat/provenance.json').read_text())
    sources = [s for s in provenance['sources'] if s['id'] in ['track-engine-source', 'track-treads-source']]
    sources.extend(source for source in existing['sources'] if source['id'] == 'kenney-voiceover-pack')
    report = dict(version=2, prepared='2026-09-10', sources=sources, files=files,
        music='Original game compositions generated by scripts/generate-combat-music.py; no external samples.',
        speech=existing['speech'], notice_only_events=existing.get('notice_only_events', {}),
        total_bytes=sum(f['bytes'] for f in files))
    (OUT/'provenance.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
