$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $projectRoot
$extractLines = @'
import fs from 'node:fs';
import ts from 'typescript';
const js = ts.transpileModule(fs.readFileSync('lib/tactical-radio.ts', 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 }
}).outputText;
const mod = await import('data:text/javascript;base64,' + Buffer.from(js).toString('base64'));
console.log(JSON.stringify(mod.RADIO_LINES));
'@
$linesJson = $extractLines | & node --input-type=module
if ($LASTEXITCODE -ne 0) { throw 'Unable to read radio script' }
$radioLines = $linesJson | ConvertFrom-Json
$rawDirectory = Join-Path $projectRoot 'work/radio-raw'
$assetDirectory = Join-Path $projectRoot 'web/audio/radio'
New-Item -ItemType Directory -Force -Path $rawDirectory, $assetDirectory | Out-Null
$voice = New-Object -ComObject SAPI.SpVoice
$englishVoice = @($voice.GetVoices() | Where-Object { $_.GetDescription() -match 'Zira.*English' })[0]
if (-not $englishVoice) { throw 'Install the Windows English (US) Zira desktop voice to regenerate these clips.' }
$voice.Voice = $englishVoice
$voice.Rate = 1
$voice.Volume = 100
foreach ($line in $radioLines.PSObject.Properties) {
  $stream = New-Object -ComObject SAPI.SpFileStream
  $stream.Format.Type = 22 # 22.05 kHz, mono, 16-bit PCM
  $stream.Open((Join-Path $rawDirectory ($line.Name + '.wav')), 3, $false)
  try {
    $voice.AudioOutputStream = $stream
    $null = $voice.Speak($line.Value)
  } finally { $stream.Close() }
}
& python (Join-Path $PSScriptRoot 'process-radio.py') $rawDirectory $assetDirectory
if ($LASTEXITCODE -ne 0) { throw 'Radio processing failed' }
$imports = @("// Generated by scripts/generate-radio.ps1. Imported assets stay out of Android.", "import type { RadioId } from './tactical-radio';")
$entries = @()
foreach ($line in $radioLines.PSObject.Properties) {
  $imports += "import $($line.Name) from '../web/audio/radio/$($line.Name).wav';"
  $entries += "  $($line.Name),"
}
$module = ($imports -join "`n") + "`nexport const RADIO_ASSETS: Record<RadioId, string> = {`n" + ($entries -join "`n") + "`n};`n"
[System.IO.File]::WriteAllText((Join-Path $projectRoot 'lib/radio-assets.ts'), $module)
Write-Output "Generated $($entries.Count) English command clips."
